services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code/app
    restart: always
    env_file:
      - .env
    command: ["fastapi", "run", "app/main.py", "--port", "8000"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  stg-network:
    external: true
